TOP=..
include $(TOP)/configure/CONFIG
#=======================================

#protocol files
DATA += itc503.proto

#database files
DB += ITC503.db

#=======================================
include $(TOP)/configure/RULES
